# Generated by Django 4.2.6 on 2023-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
