# Generated by Django 4.2.6 on 2023-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_remove_product_age_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='champions/images'),
        ),
    ]
